name: C/C++ Lint

on:
  push:
    branches: [ main, master ]
#     paths:
#       - '**.c'
#       - '**.cpp'
  pull_request:
    branches: [ main, master ]
#     paths:
#       - '**.c'
#       - '**.cpp'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: C/C++ code linter
        uses: ArtificialAmateur/cpp-linter-action@0.01
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
