name: C/C++ Lint

on:
  push:
    branches: [ main, master ]
#     paths:
#       - '**.c'
#       - '**.cpp'
  pull_request:
    branches: [ main, master ]
#     paths:
#       - '**.c'
#       - '**.cpp'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Clang
        uses: actions/setup-clang@v1
        with:
          clang-version: "12"
          tool-cache: true

      - name: Run clang-tidy
        run: |
          clang-tidy --version
          clang-tidy src/*.cpp src/*.c
